import os
KNOTS2MS = 0.514444
THRESHOLD_SPEED_OPT1 = 118
THRESHOLD_SPEED_OPT2 = 166
ADMS = [
    
]
ADMS2 = [
    
]
AA_DATA_DIR = os.getenv("AA_DATA_DIR")
AA_DATA_DIR_NEW = os.getenv("AA_DATA_DIR_NEW")